name: razorpay_demo
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.3.4
  firebase_core: ^2.1.1
  cloud_functions: ^4.0.3
  intl: ^0.17.0
  js: 0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: fonts/Poppins-Bold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/Poppins-Medium.ttf
          weight: 400
        - asset: fonts/Poppins-Regular.ttf
          weight: 300
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
