// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQE2ysk9qPcejeNghYCa9Ic3FEtG9GHg',
    appId: '1:135747276353:web:1652b28f6d7db272d640c0',
    messagingSenderId: '135747276353',
    projectId: 'razorpay-demo-4d028',
    authDomain: 'razorpay-demo-4d028.firebaseapp.com',
    storageBucket: 'razorpay-demo-4d028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4Cwq23v9_Mx12rvbcnJgIWu4lwFTGUU',
    appId: '1:135747276353:android:838e3330354feac7d640c0',
    messagingSenderId: '135747276353',
    projectId: 'razorpay-demo-4d028',
    storageBucket: 'razorpay-demo-4d028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-R1x2sBJ_zFaAY5z2yXfv1sdAeDa0GpE',
    appId: '1:135747276353:ios:c6bcadcac1f864b2d640c0',
    messagingSenderId: '135747276353',
    projectId: 'razorpay-demo-4d028',
    storageBucket: 'razorpay-demo-4d028.appspot.com',
    iosClientId: '135747276353-9g7928hbv7qqva7oq48adi9abqc2og6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.razorpayDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-R1x2sBJ_zFaAY5z2yXfv1sdAeDa0GpE',
    appId: '1:135747276353:ios:c6bcadcac1f864b2d640c0',
    messagingSenderId: '135747276353',
    projectId: 'razorpay-demo-4d028',
    storageBucket: 'razorpay-demo-4d028.appspot.com',
    iosClientId: '135747276353-9g7928hbv7qqva7oq48adi9abqc2og6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.razorpayDemo',
  );
}
